### ISSUE TITLE
refactor: rules configuration

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/tripsu#43]
We need to settle on a schema for specifying rules. The [current rule specification system](https://github.com/sdsc-ordes/tripsu/blob/main/tests/data/config.yaml) is verbose and inconsistent (e.g. singular / plural):

Objective: structure for rule definitions is cleare and easy to extend.

Requirement:
* [ ] keys are concise and easy to understand+remember
* [ ] simple nesting
* [ ] consistent naming

Initial proposal:
```yaml
# Pseudonymize subject URIs
subjects:
  of_type:
    - "http://example.org/Person"

# Pseudonymize object values
objects:
  on_predicate:
    - "http://example.org/address"
  on_type:  # NOTE: not currently supported
    - "http://example.org/UserAccount"
  on_type_predicate:
    "http://example.org/Person":
      - "https://example.org/name"
```
