### ISSUE TITLE
feat: support CURIES in config

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/tripsu#60]
due to the lack of inference, tripsu configs can be very redundant.
To reduce this redundancy, we could support compact uris using something like this in the config file:

```yaml
prefixes:
  "schema": "<https://schema.org/>"
  "ex": "<http://example.org/>"

nodes:
  of_type:
    - "schema:Person"
    - "schema:Organization"

objects:
  on_type_predicate:
    "schema:Person":
        - "schema:birthPlace"
  on_predicate:
     - "ex:password"
     - "ex:email"
     - "ex:userName"
```
