### ISSUE TITLE
rules.rs silently ignoring poorly formatted URIs

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/tripsu#67]
when running the benchmark in #66 I noticed that nothing was being pseudonymized in the benchmark.

This is because the rules file used did not enclose URI in angle brackets (`<...>`). As a results, the URIs were not picked up and nothing was pseudonymized.

This is unwanted behaviour, we should instead inform the user that the URI formatting is invalid and error out.

**Comment by cmdoret** [comment]
This can be reproduced with the test data using these rules:

```yaml
# ./bad_rules.yaml
# Invert the matching rules for nodes and objects.
invert: false


# hash URIs of people and online accounts
nodes:
  of_type:
  - "http://example.org/Person" # All nodes which are rdf:type Person
  - "http://xmlns.com/foaf/0.1/OnlineAccount" # "" OnlineAccount

objects:
  # hash accesscode values for all nodes
  on_predicate:
  # Full URIs are also supported
  - "http://schema.org/accessCode"
  # hash name only for instances of person and online account
  on_type_predicate:
    # No brackets is assumed to be a compact URI
    "http://example.org/OnlineAccount":
    - "http://schema.org/name"
    "http://xmlns.com/foaf/0.1/Person":
    - "http://schema.org/name"
```


```bash
tripsu index tests/data/test.nt > bad_index.json 
tripsu pseudo -x bad_index.json -r bad_rules.yaml -o bad_output.nt tests/data/test.nt
```
